### ISSUE TITLE
Unable to install codesake-dawn gem 

### ISSUE THREAD

**Issue by lohithmv019** [thesp0nge/dawnscanner#61]
I am not able to install codesake-dawn gem because of the dependency on multiple versions of "mime-types" gem.

grit requires mime-types (~> 1.15)(mime type 2 will not work)
rest-client requires mime-types (>= 1.16)
mechanize requires mime-types (~> 2.0)

I tried installing both version of the "mime-types" gem (1.25 and 2.2) then gem installed successfully but i am unable to run dawn,when try to run dawn I am getting following error 
" `raise_if_conflicts': Unable to activate grit-2.5.0, because mime-types-2.2 conflicts with mime-types (~> 1.15) (Gem::LoadError)"

I am running ubuntu 13.10 and RVM with ruby 1.9.3 and ruby 2.1

Please let me know if there is any work around for this ?

**Comment by Chillibear** [comment]
It's the `codesake-commons` gem that I think is bringing in the problem.  It requires any version of `mechanize` and as tecknicaltom says the current version is 2.7.3 where the dependency on `mime-types` switched to version 2.  You could try hacking the gem spec of your copy of `code sake-commons` to specify an older version of `mechanize`, _i.e._ `gem.add_dependency 'mechanize', '<= 2.7.2'` in `codesake-commons.gemspec`.  I just encountered the same problem myself and this temporarily fixed it by getting the slightly older version of `mechanize` installed.

The long term solution is probably to switch to `Rugged` rather than `Grit`
